export const authConstants = {
  INSERT_REQUEST: "INSERT_REQUEST",
  INSERT_FAILURE: "INSERT_FAILURE",
  INSERT_SUCCESS: "INSERT_SUCCESS",
  
  LOGOUT_REQUEST: "LOGOUT_REQUEST",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  LOGOUT_FAILURE: "LOGOUT_FAILURE",
  
  INITIAL_REQUEST: "INITIAL_REQUEST",
  INITIAL_SUCCESS: "INITIAL_SUCCESS",
  INITIAL_FAILURE: "INITIAL_FAILURE",
  
  EDIT_REQUEST: "EDIT_REQUEST",
  EDIT_FAILURE: "EDIT_FAILURE",
  EDIT_SUCCESS: "EDIT_SUCCESS",
  
};